title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://clees1.github.io/portfoliotesting2

aux_links:
  Template Repository: https://clees1.github.io/portfoliotesting2
